source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TwoThumbsSlider_Example', :exclusive => true do
  pod "TwoThumbsSlider", :path => "../"
end

target 'TwoThumbsSlider_Tests', :exclusive => true do
  pod "TwoThumbsSlider", :path => "../"

  
end
